---
name: Deliver

on: 
  push:
    branches: ["master"]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to registry
        run: >
          echo ${{ secrets.REGISTRY_PASSWORD }}
          | sudo docker login
          -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      
      - name: Build image
        run: >
          sudo docker build . --file FigureCollection/Dockerfile
          --tag niels040/figure-colldction-s3:latest-backend
      
      - name: Push to registry
        run: sudo docker push niels040/figure-colldction-s3:latest-backend
